import React from 'react';

const TestimonialArea = () => {
  return (
    <section className="testimonial-area">
      <div className="custom-container">
        <div className="testimonial-slider-wrap">
          <div className="testimonial-slider swiper">
            <div className="swiper-wrapper">
              <div className="swiper-slide testimonial-item">
                <div className="testimonial-item-body">
                  <img className="animation-slide-right bg-shape" src="assets/imgs/bg-shape-3.svg" alt="Shape" />
                  <span className="platform-name">
                    <img src="assets/imgs/icon-linkedin.svg" alt="Icon" />
                  </span>
                  <h1>Platform helped me to increase my sales and revenue generated by bluebase technologies</h1>
                  <p>One aspect that sets IT Services apart is their proactive approach to security. In today's digital landscape, protecting our sensitive data is of utmost importance.</p>
                  <div className="author-box d-flex align-items-center">
                    <img src="assets/imgs/testimonial-1.jpg" alt="Testimonial" />
                    <div className="author-box-content">
                      <h4>Serana Belluci</h4>
                      <p>Product Designer</p>
                    </div>
                  </div>
                </div>
              </div>
              <div className="swiper-slide testimonial-item">
                <div className="testimonial-item-body">
                  <img className="bg-shape" src="assets/imgs/bg-shape-3.svg" alt="Shape" />
                  <span className="platform-name">
                    <img src="assets/imgs/icon-linkedin.svg" alt="Icon" />
                  </span>
                  <h1>Bluebase give the best service and top customer support. Really like to have more projects with you</h1>
                  <p>One aspect that sets IT Services apart is their proactive approach to security. In today's digital landscape, protecting our sensitive data is of utmost importance.</p>
                  <div className="author-box d-flex align-items-center">
                    <img src="assets/imgs/testimonial-2.jpg" alt="Testimonial" />
                    <div className="author-box-content">
                      <h4>Megan Clarke</h4>
                      <p>CEO, Sanlab</p>
                    </div>
                  </div>
                </div>
              </div>
              <div className="swiper-slide testimonial-item">
                <div className="testimonial-item-body">
                  <img className="bg-shape" src="assets/imgs/bg-shape-3.svg" alt="Shape" />
                  <span className="platform-name">
                    <img src="assets/imgs/icon-linkedin.svg" alt="Icon" />
                  </span>
                  <h1>We’ve been using bluebase for a few years, It is very simple and easy to approach team and management</h1>
                  <p>One aspect that sets IT Services apart is their proactive approach to security. In today's digital landscape, protecting our sensitive data is of utmost importance.</p>
                  <div className="author-box d-flex align-items-center">
                    <img src="assets/imgs/testimonial-3.jpg" alt="Testimonial" />
                    <div className="author-box-content">
                      <h4>Rachel Olsem</h4>
                      <p>Full Stack Developer</p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          {/* Navigation buttons */}
          <div className="swiper-button-prev"><i className="iconoir-arrow-left"></i></div>
          <div className="swiper-button-next"><i className="iconoir-arrow-right"></i></div>
        </div>
      </div>
    </section>
  );
};

export default TestimonialArea;
